# File format : YAML
# https://yaml.org/

# The _key value is necessary in the database.
# It is a MD5 hash obtained with :
#   echo "[osname] [osversion]" | md5sum
# 
#   echo "Debian GNU/Linux 12" | md5sum
#     3ae9b9ff69a78d614864f1957778fecb

list:
  - os:
    _key: "f927102807a513e0e1d0eea9e7505b57"
    osname: "Linux Mint"
    osversion: "20"
    repositories:
      - "deb http://packages.linuxmint.com ulyana main upstream import backport #id:linuxmint_main"
      - "deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse"
      - "deb http://archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse"
      - "deb http://archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse"
      - "deb http://security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse"
      - "deb http://archive.canonical.com/ubuntu/ focal partner"

  - os:
    _key: "67d2fc0cbcb12e24cc40639dc9de1888"
    osname: "Linux Mint"
    osversion: "20.1"
    repositories:
      - "deb http://packages.linuxmint.com ulyssa main upstream import backport #id:linuxmint_main"
      - "deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse"
      - "deb http://archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse"
      - "deb http://archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse"
      - "deb http://security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse"
      - "deb http://archive.canonical.com/ubuntu/ focal partner"

  - os:
    _key: "56bb506e24d8ff19bc4244b2f8d3543e"
    osname: "Linux Mint"
    osversion: "20.2"
    repositories:
      - "deb http://packages.linuxmint.com uma main upstream import backport #id:linuxmint_main"
      - "deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse"
      - "deb http://archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse"
      - "deb http://archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse"
      - "deb http://security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse"
      - "deb http://archive.canonical.com/ubuntu/ focal partner"

  - os:
    _key: "093005508bb26f610f57a78826b84b3b"
    osname: "Linux Mint"
    osversion: "21"
    repositories:
      - "deb http://packages.linuxmint.com vanessa main upstream import backport #id:linuxmint_main"
      - "deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse"
      - "deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse"
      - "deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse"
      - "deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse"

  - os:
    _key: "3ae9b9ff69a78d614864f1957778fecb"
    osname: "Debian GNU/Linux"
    osversion: "12"
    repositories:
      - "deb http://ftp.fr.debian.org/debian/ bookworm main non-free-firmware"
      - "deb-src http://ftp.fr.debian.org/debian/ bookworm main non-free-firmware"
      - "deb http://security.debian.org/debian-security bookworm-security main non-free-firmware"
      - "deb-src http://security.debian.org/debian-security bookworm-security main non-free-firmware"
      - "deb http://ftp.fr.debian.org/debian/ bookworm-updates main non-free-firmware"
      - "deb-src http://ftp.fr.debian.org/debian/ bookworm-updates main non-free-firmware"


  - os:
    _key: "4b340a5a0c5dd1f59bf122caa5a8761d"
    osname: "Ubuntu"
    osversion: "22.04"
    repositories:
      - "deb http://fr.archive.ubuntu.com/ubuntu/ jammy main restricted"
      - "deb http://fr.archive.ubuntu.com/ubuntu/ jammy-updates main restricted"
      - "deb http://fr.archive.ubuntu.com/ubuntu/ jammy universe"
      - "deb http://fr.archive.ubuntu.com/ubuntu/ jammy-updates universe"
      - "deb http://fr.archive.ubuntu.com/ubuntu/ jammy multiverse"
      - "deb http://fr.archive.ubuntu.com/ubuntu/ jammy-updates multiverse"
      - "deb http://fr.archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse"
      - "deb http://security.ubuntu.com/ubuntu jammy-security main restricted"
      - "deb http://security.ubuntu.com/ubuntu jammy-security universe"
      - "deb http://security.ubuntu.com/ubuntu jammy-security multiverse"

  - os:
    _key: "378a77e6b2543c4a08c9ef94bfa344d2"
    osname: "Ubuntu"
    osversion: "23.04"
    repositories:
      - "deb http://fr.archive.ubuntu.com/ubuntu lunar main restricted"
      - "deb http://fr.archive.ubuntu.com/ubuntu lunar-updates main restricted"
      - "deb http://fr.archive.ubuntu.com/ubuntu lunar universe"
      - "deb http://fr.archive.ubuntu.com/ubuntu lunar-updates universe"
      - "deb http://fr.archive.ubuntu.com/ubuntu lunar multiverse"
      - "deb http://fr.archive.ubuntu.com/ubuntu lunar-updates multiverse"
      - "deb http://fr.archive.ubuntu.com/ubuntu lunar-backports main restricted universe multiverse"
      - "deb http://fr.archive.ubuntu.com/ubuntu lunar-security main restricted"
      - "deb http://fr.archive.ubuntu.com/ubuntu lunar-security universe"
      - "deb http://fr.archive.ubuntu.com/ubuntu lunar-security multiverse"

  - os:
    _key: "1cbb0e9b35e9ccba858d547fb891ee0a"
    osname: "Ubuntu"
    osversion: "23.10"
    repositories:
      - "deb http://fr.archive.ubuntu.com/ubuntu/ mantic main restricted"
      - "deb http://fr.archive.ubuntu.com/ubuntu/ mantic-updates main restricted"
      - "deb http://fr.archive.ubuntu.com/ubuntu/ mantic universe"
      - "deb http://fr.archive.ubuntu.com/ubuntu/ mantic-updates universe"
      - "deb http://fr.archive.ubuntu.com/ubuntu/ mantic multiverse"
      - "deb http://fr.archive.ubuntu.com/ubuntu/ mantic-updates multiverse"
      - "deb http://fr.archive.ubuntu.com/ubuntu/ mantic-backports main restricted universe multiverse"
      - "deb http://security.ubuntu.com/ubuntu/ mantic-security main restricted"
      - "deb http://security.ubuntu.com/ubuntu/ mantic-security universe"
      - "deb http://security.ubuntu.com/ubuntu/ mantic-security multiverse"

  - os:
    _key: "53dbf8829e09b0e706cdb36a1099a116"
    osname: "CentOS Stream"
    osversion: "9"
    repositories:
      - "Not applicable at the moment (fastest mirror)"
      
  - os:
    _key: "f733c65385f72716dc82ebff46474e72"
    osname: "Oracle Linux Server"
    osversion: "9.2"
    repositories:
      - "Not applicable at the moment (fastest mirror)"