# File format : YAML
# https://yaml.org/

# The _key value is necessary in the database.
# It is a MD5 hash obtained with :
#   echo "$(date)" | md5sum
# Since there is nothing definitive in a script, the hash
# is based on the date and time of the creation.
# 
#   echo "$(date)" | md5sum
#     5f221571aecfcdd203d30957cf9896a0

# Guidelines to write the scripts content :
  # - can be executed multiple times without problem, meaning it has
  # to check whether the job is already done or not before doing anything
  # - respect the YAML indentation
  # - " ' must be escaped \", as if it were
  # going to be printed by a "print!()"
  # - until a better solution is found, each REPS script has to be compatible
  # with all clients OS possible (Ubuntu, Mint, Debian, CentOS)

list:
  - script:
    _key: "67e356d490e1f6bd279e6b8f430f9b99"
    role: "client"
    compatible_with:
      - "56bb506e24d8ff19bc4244b2f8d3543e" # Linux Mint 20.2
      - "093005508bb26f610f57a78826b84b3b" # Linux Mint 21
    content: |
      mv /etc/apt/sources.list.d/official-package-repositories.list /etc/apt/sources.list.d/official-package-repositories.list.old
      cat /etc/apt/sources.list.d/official-package-repositories.list.old | grep -v \'^#\' | grep . | sed \"s\\http://\\http://$IP_DISS:3142/\\g\" | sed \"s\\https://\\https://$IP_DISS:3142/\\g\" > /etc/apt/sources.list.d/karnaboo.list
      
  - script:
    _key: "7535eaca819afbe6836f184b7c237acd"
    role: "diss"
    compatible_with:
      - "093005508bb26f610f57a78826b84b3b" # Linux Mint 21
    content: |
      mv /etc/apt/sources.list.d/official-package-repositories.list /etc/apt/sources.list.d/official-package-repositories.list.old
      cat /etc/apt/sources.list.d/official-package-repositories.list.old | grep -v \'^#\' | grep . | sed \"s\\http://\\http://$IP_REPS:3142/\\g\" | sed \"s\\https://\\https://$IP_REPS:3142/\\g\" > /etc/apt/sources.list.d/karnaboo.list
      apt update
      DEBIAN_FRONTEND=noninteractive apt install -y apt-cacher-ng
      cp /etc/apt-cacher-ng/acng.conf /etc/apt-cacher-ng/acng.conf.old
      echo \"PassThroughPattern: ^(.*):443$\" >> /etc/apt-cacher-ng/acng.conf
      echo \"VfilePatternEx: ^(/\\?release[0-9]+&arch.*|.*/RPM-GPG-KEY-examplevendor)$\" >> /etc/apt-cacher-ng/acng.conf
      echo \"Proxy: http://$IP_REPS:3142\" >> /etc/apt-cacher-ng/acng.conf
      systemctl restart apt-cacher-ng.service
      systemctl reboot

  - script:
    _key: "d909df38b28abe8e436b56d219a26545"
    role: "reps"
    compatible_with:
      - "093005508bb26f610f57a78826b84b3b" # Linux Mint 21
    content: |
      DEBIAN_FRONTEND=noninteractive apt install -y apt-cacher-ng
      echo \"PassThroughPattern: ^(.*):443$\" >> /etc/apt-cacher-ng/acng.conf
      echo \"VfilePatternEx: ^(/\\?release[0-9]+&arch.*|.*/RPM-GPG-KEY-examplevendor)$\" >> /etc/apt-cacher-ng/acng.conf
      systemctl reboot

  - script:
    _key: "16e1ff6dfd8b19c4c7d4eb55f3a4152a"
    role: "client"
    compatible_with:
      - "4b340a5a0c5dd1f59bf122caa5a8761d" # Ubuntu 22.04
      - "378a77e6b2543c4a08c9ef94bfa344d2" # Ubuntu 23.04
      - "1cbb0e9b35e9ccba858d547fb891ee0a" # Ubuntu 23.10
      - "3ae9b9ff69a78d614864f1957778fecb" # Debian 12
    content: |
      mv /etc/apt/sources.list /etc/apt/sources.list.old
      cat /etc/apt/sources.list.old | grep -v \'^#\' | grep . | sed \"s\\http://\\http://$IP_DISS:3142/\\g\" | sed \"s\\https://\\https://$IP_DISS:3142/\\g\" > /etc/apt/sources.list.d/karnaboo.list

  - script:
    _key: "6c55e445df11d0eacef1178a94d57603"
    role: "diss"
    compatible_with:
      - "4b340a5a0c5dd1f59bf122caa5a8761d" # Ubuntu 22.04
      - "378a77e6b2543c4a08c9ef94bfa344d2" # Ubuntu 23.04
      - "1cbb0e9b35e9ccba858d547fb891ee0a" # Ubuntu 23.10
    content: |
      mv /etc/apt/sources.list /etc/apt/sources.list.old
      cat /etc/apt/sources.list.old | grep -v \'^#\' | grep . | sed \"s\\http://\\http://$IP_REPS:3142/\\g\" | sed \"s\\https://\\https://$IP_REPS:3142/\\g\" > /etc/apt/sources.list.d/karnaboo.list
      apt update
      DEBIAN_FRONTEND=noninteractive apt install -y apt-cacher-ng
      cp /etc/apt-cacher-ng/acng.conf /etc/apt-cacher-ng/acng.conf.old
      echo \"PassThroughPattern: ^(.*):443$\" >> /etc/apt-cacher-ng/acng.conf
      echo \"VfilePatternEx: ^(/\\?release[0-9]+&arch.*|.*/RPM-GPG-KEY-examplevendor)$\" >> /etc/apt-cacher-ng/acng.conf
      echo \"Proxy: http://$IP_REPS:3142\" >> /etc/apt-cacher-ng/acng.conf
      systemctl restart apt-cacher-ng.service
      systemctl reboot

  - script:
    _key: "ec6394fbb6161fa2f8aa2e897fc3a400"
    role: "reps"
    compatible_with:
      - "4b340a5a0c5dd1f59bf122caa5a8761d" # Ubuntu 22.04
      - "378a77e6b2543c4a08c9ef94bfa344d2" # Ubuntu 23.04
      - "1cbb0e9b35e9ccba858d547fb891ee0a" # Ubuntu 23.10
    content: |
      DEBIAN_FRONTEND=noninteractive apt install -y apt-cacher-ng
      echo \"PassThroughPattern: ^(.*):443$\" >> /etc/apt-cacher-ng/acng.conf
      echo \"VfilePatternEx: ^(/\\?release[0-9]+&arch.*|.*/RPM-GPG-KEY-examplevendor)$\" >> /etc/apt-cacher-ng/acng.conf
      systemctl reboot

  - script:
    _key: "f6598cc0bfcb76e5597e50d9a319fef6"
    role: "client"
    compatible_with:
      - "53dbf8829e09b0e706cdb36a1099a116" # CentOS Stream 9
    content: |
      echo \"proxy=http://$IP_DISS:3142\" >> /etc/dnf/dnf.conf

  - script:
    _key: "71e4f2b81cf3e7a89a9866334aba5d58"
    role: "diss"
    compatible_with:
      - "53dbf8829e09b0e706cdb36a1099a116" # CentOS Stream 9
    content: |
      echo \"proxy=http://$IP_REPS:3142\" >> /etc/dnf/dnf.conf
      dnf install --allowerasing -y apt-cacher-ng
      firewall-cmd --permanent --add-port=3142/tcp
      firewall-cmd --reload
      echo \"PassThroughPattern: ^(.*):443$\" >> /etc/apt-cacher-ng/acng.conf
      echo \"VfilePatternEx: ^(/\\?release[0-9]+&arch.*|.*/RPM-GPG-KEY-examplevendor)$\" >> /etc/apt-cacher-ng/acng.conf
      echo \"Proxy: http://$IP_REPS:3142\" >> /etc/apt-cacher-ng/acng.conf
      systemctl enable apt-cacher-ng.service
      systemctl start apt-cacher-ng.service
      systemctl reboot

  - script:
    _key: "ee5a8caf8a996c07ea94a6ff770a4d4a"
    role: "reps"
    compatible_with:
      - "53dbf8829e09b0e706cdb36a1099a116" # CentOS Stream 9
    content: |
      dnf install --allowerasing -y apt-cacher-ng
      firewall-cmd --permanent --add-port=3142/tcp
      firewall-cmd --reload
      echo \"PassThroughPattern: ^(.*):443$\" >> /etc/apt-cacher-ng/acng.conf
      echo \"VfilePatternEx: ^(/\\?release[0-9]+&arch.*|.*/RPM-GPG-KEY-examplevendor)$\" >> /etc/apt-cacher-ng/acng.conf
      systemctl enable apt-cacher-ng.service
      systemctl start apt-cacher-ng.service
      systemctl reboot

  - script:
    _key: "92cba19d202057fb8c4d6f519fdede5e"
    role: "diss"
    compatible_with:
      - "3ae9b9ff69a78d614864f1957778fecb" # Debian 12
    content: |
      mv /etc/apt/sources.list /etc/apt/sources.list.old
      cat /etc/apt/sources.list.old | grep -v \'^#\' | grep . | sed \"s\\http://\\http://$IP_REPS:3142/\\g\" | sed \"s\\https://\\https://$IP_REPS:3142/\\g\" > /etc/apt/sources.list.d/karnaboo.list
      apt update
      DEBIAN_FRONTEND=noninteractive apt install -y apt-cacher-ng ufw
      ufw allow 3142/tcp
      ufw enable
      cp /etc/apt-cacher-ng/acng.conf /etc/apt-cacher-ng/acng.conf.old
      echo \"PassThroughPattern: ^(.*):443$\" >> /etc/apt-cacher-ng/acng.conf
      echo \"VfilePatternEx: ^(/\\?release[0-9]+&arch.*|.*/RPM-GPG-KEY-examplevendor)$\" >> /etc/apt-cacher-ng/acng.conf
      echo \"Proxy: http://$IP_REPS:3142\" >> /etc/apt-cacher-ng/acng.conf
      systemctl restart apt-cacher-ng.service
      systemctl reboot

  - script:
    _key: "c12a2f520934c46b67317c5bc0f4452a"
    role: "reps"
    compatible_with:
      - "3ae9b9ff69a78d614864f1957778fecb" # Debian 12
    content: |
      DEBIAN_FRONTEND=noninteractive apt install -y apt-cacher-ng ufw
      ufw allow 3142/tcp
      ufw enable
      echo \"PassThroughPattern: ^(.*):443$\" >> /etc/apt-cacher-ng/acng.conf
      echo \"VfilePatternEx: ^(/\\?release[0-9]+&arch.*|.*/RPM-GPG-KEY-examplevendor)$\" >> /etc/apt-cacher-ng/acng.conf
      systemctl restart apt-cacher-ng.service
      systemctl reboot
