[default]
address = "0.0.0.0"
port = 8000
workers = 16
max_blocking = 512
keep_alive = 5
ident = "Rocket"
ip_header = "X-Real-IP"
log_level = "critical"
temp_dir = "/tmp"
cli_colors = true
# secret_key = "xxxx"